version: '2'

services:
  frontend:
    build: frontend
    ports:
      - 8501:8501
    depends_on:
      - backend
    volumes:
        - ./APP:.
  backend:
    build: backend
    ports:
      - 8080:8080
    volumes:
      - ./APP:.
