name: publish
run-name: ${{ github.actor }} creates the app
on: [push]
jobs: 
    compose:
        runs-on: ubuntu-latest
        steps: 
            - name: compose build
              run: docker compose build -f "docker-compose.yml"
            - name: compose up
              run: docker compose up -f "docker-compose.yml"